-- This fork supports only Portal 2 beta build 852_0.
INSERT INTO games (game_id, name, game_mod, app_id, sourcemod)
VALUES (1, "Portal 2 Beta (852_0)", "portal2", NULL, 0);

-- all BSPs from 852_0. type: 1 = single-player, 2 = co-op.
INSERT INTO maps (game_id, name, alias, type, best_time_id, best_portals_id, chapter, auto_fullbright) VALUES
  (1, "devtest", "Devtest", 1, NULL, NULL, 0, 0),
  (1, "videotest", "Video Test", 1, NULL, NULL, 0, 0),
  (1, "p2_lab_start_01", "Lab Start 1", 1, NULL, NULL, 1, 0),
  (1, "p2_lab_start_02", "Lab Start 2", 1, NULL, NULL, 1, 0),
  (1, "p2_lab_prehub_1", "Pre-Hub 1", 1, NULL, NULL, 1, 0),
  (1, "p2_lab_turrets", "Turrets", 1, NULL, NULL, 1, 0),
  (1, "p2_lab_suctionturrets_1", "Suction Turrets", 1, NULL, NULL, 1, 0),
  (1, "p2_lab_hub_1", "Hub 1", 1, NULL, NULL, 1, 0),
  (1, "p2_lab_prehub_2", "Pre-Hub 2", 1, NULL, NULL, 2, 0),
  (1, "p2_lab_lasers_1", "Lasers", 1, NULL, NULL, 2, 0),
  (1, "p2_lab_hub_2", "Hub 2", 1, NULL, NULL, 2, 0),
  (1, "p2_lab_prehub_2a", "Pre-Hub 2A", 1, NULL, NULL, 3, 0),
  (1, "p2_lab_slowfield_1", "Slow Field", 1, NULL, NULL, 3, 0),
  (1, "p2_lab_hub_3", "Hub 3", 1, NULL, NULL, 3, 0),
  (1, "p2_lab_catapult", "Catapult", 1, NULL, NULL, 4, 0),
  (1, "p2_lab_hub_4", "Hub 4", 1, NULL, NULL, 4, 0),
  (1, "p2_lab_wall_01", "Wall", 1, NULL, NULL, 5, 0),
  (1, "p2_lab_hub_5", "Hub 5", 1, NULL, NULL, 5, 0),
  (1, "p2_lab_mixup", "Mixup", 1, NULL, NULL, 6, 0),
  (1, "p2_lab_hub_6", "Hub 6", 1, NULL, NULL, 6, 0),
  (1, "mp_coop_start", "Calibration", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_button_tower", "Button Tower", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_catapult_1", "Catapult 1", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_catapult_2", "Catapult 2", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_catapult_wall_intro", "Catapult Wall Intro", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_come_along", "Come Along", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_doors", "Doors", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_double_catch", "Double Catch", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_fling_1", "Fling 1", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_fling_3", "Fling 3", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_laser_1", "Laser 1", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_laser_2", "Laser 2", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_laser_3", "Laser 3", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_laser_bypass", "Laser Bypass", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_laser_crusher", "Laser Crusher", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_laser_redirect", "Laser Redirect", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_mic_calibration", "Microphone Calibration", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_race_1", "Race 1", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_race_2", "Race 2", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_race_3", "Race 3", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_rat_maze", "Rat Maze", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_trap_1", "Trap 1", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_turret_walls", "Turret Walls", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_vista", "Vista", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_1", "Wall 1", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_2", "Wall 2", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_3", "Wall 3", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_5", "Wall 5", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_6", "Wall 6", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_block", "Wall Block", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_catch", "Wall Catch", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_intro", "Wall Intro", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_stop", "Wall Stop", 2, NULL, NULL, 0, 0),
  (1, "mp_coop_wall_straight_jump", "Wall Straight Jump", 2, NULL, NULL, 0, 0);
